### ISSUE TITLE
Last will configuration is missing for mqtt

### ISSUE THREAD

**Issue by flamedmg** [lubosmato/esp32-essentials#3]
I would really like to have this feature. What do you think about it?

**Comment by lubosmato** [comment]
I added last will configuration: https://github.com/lubosmato/esp32-essentials/commit/7baf5811b146991831b856b69d4e243a950e8db3

But I couldn't properly send LWT messages with different qos than 0.

**Comment by flamedmg** [comment]
What you did works great! thank you!
