### ISSUE TITLE
Things i would like to be enhanced

### ISSUE THREAD

**Issue by flamedmg** [lubosmato/esp32-essentials#4]
Thank you for your work! I really appreciate you starter project.
Here is a list of things i miss currently. May be you would want to implement them:

- [x] i would like to turn off access point mode. Currently app if has troubles with wifi connection, even if it's configured, goes to access point mode. This doesn't seems right. If wifi is configured, but wifi isn't available it's logically correct to keep trying or at least this behaviour should be configured imho.
- [x] i miss wifi connected or mqtt connected events. I want to start some things after one of both events are complete, but currently i do not see way how to achieve that. 
- [x] mqtt client Subscibe/Publish method always appends prefix. That makes impossible to subscribe to other device topics or to publish messages to other device topics too.

Please let me know you thoughts about this.

**Comment by lubosmato** [comment]
Thank you for these suggestions! What you described makes sense to me and I consider it as design flaws so I fixed it.

- Access point mode is not automatically turned on now. It is up to client's code if settings server and access point mode is needed.
- Wifi and Mqtt now provides a way to specify client's callbacks (connect and disconnect).
- You can leave mqtt prefix blank and then no prefix will be added to your topics. The use-case of the prefix comes from MQTT best practices *Embed a unique identifier or the Client Id into the topic* from https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/

Examples are updated so take a look and let me know if it is ok.

**Comment by flamedmg** [comment]
everything works just great!
