### ISSUE TITLE
Compile fails - need help

### ISSUE THREAD

**Issue by RudyFiero** [lubosmato/esp32-essentials#5]
Your esp32-essentials is what I had been looking for. Unfortunately I don't know enough to get it to work. I hope you can help and show me what I need to do to correctly used your code.

I followed the steps in the readme on the front page. Steps 1 - 4 seemed to go ok. When I used configure in the esp-idf extension I had an error and it states the configuration is incomplete. 

I am new to working with esp-idf. I have gone through some examples. I have had more success using the command line that using the VS Code extension. But since you listed it as a method I thought I would give it a try again. 

What I did was take the blink example sketch as my base. I then followed the steps in the readme. I changed the blink.c filename to main.cpp since that is what you have listed in step 4.  I'm sure this was incorrect since I did not change anything in the blink.c file. (now called main.cpp)

I then selected the device target, ESP32-S2, that I have been using. (selecting ESP32 also produced the errors) 

![menuconfig](https://user-images.githubusercontent.com/10385754/127941386-a85b1487-ad88-4d2f-856b-c2613c7c2e7f.PNG)

The status bar goes to the right, but it does not complete. I have to cancel.

My first Cmake file, 

```
# The following five lines of boilerplate have to be in your project's
# CMakeLists in this exact order for cmake to work correctly
cmake_minimum_required(VERSION 3.5)

set(CMAKE_CXX_STANDARD 20) # <--

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(blink)

target_add_binary_data(${CMAKE_PROJECT_NAME}.elf "components/essentials/resources/web/dist/app.js.gz" TEXT) # <-- (only needed by `essentials::SettingsServer`)
target_add_binary_data(${CMAKE_PROJECT_NAME}.elf "components/essentials/resources/web/dist/index.html.gz" TEXT) # <-- (only needed by `essentials::SettingsServer`)
```

Cmake in main directory,

```
idf_component_register(SRCS "blink.c"
                    INCLUDE_DIRS ".")
idf_component_register(
    SRCS "main.cpp"
    REQUIRES essentials
)
```

[CMakeOutput.log](https://github.com/lubosmato/esp32-essentials/files/6920356/CMakeOutput.log)

Can you tell me what I have done wrong, and what i need to do to get this corrected?

**Comment by RudyFiero** [comment]
I used my computer at work to compile. I have got further. I started over. I will have to see what I did different at home. Now it seems to have accepted the setup. It got near the end of the compile, and produced the following.

```
esptool.py v3.1-dev
Merged 1 ELF section
Generated C:/Users/iau/try/blink/build/bootloader/bootloader.bin
[854/865] Building CXX object esp-idf/essentials/CMakeFiles/__idf_essentials.dir/source/wifi.cpp.obj
FAILED: esp-idf/essentials/CMakeFiles/__idf_essentials.dir/source/wifi.cpp.obj 
ccache C:\Users\iau\.espressif\tools\xtensa-esp32s2-elf\esp-2020r3-8.4.0\xtensa-esp32s2-elf\bin\xtensa-esp32s2-elf-g++.exe  -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -Iconfig -I../components/essentials/include -IC:/Users/iau/esp/esp-idf/components/newlib/platform_include -IC:/Users/iau/esp/esp-idf/components/freertos/include -IC:/Users/iau/esp/esp-idf/components/freertos/port/xtensa/include -IC:/Users/iau/esp/esp-idf/components/esp_hw_support/include -IC:/Users/iau/esp/esp-idf/components/esp_hw_support/port/esp32s2/. -IC:/Users/iau/esp/esp-idf/components/esp_hw_support/port/esp32s2/private_include -IC:/Users/iau/esp/esp-idf/components/heap/include -IC:/Users/iau/esp/esp-idf/components/log/include -IC:/Users/iau/esp/esp-idf/components/lwip/include/apps -IC:/Users/iau/esp/esp-idf/components/lwip/include/apps/sntp -IC:/Users/iau/esp/esp-idf/components/lwip/lwip/src/include -IC:/Users/iau/esp/esp-idf/components/lwip/port/esp32/include -IC:/Users/iau/esp/esp-idf/components/lwip/port/esp32/include/arch -IC:/Users/iau/esp/esp-idf/components/soc/include -IC:/Users/iau/esp/esp-idf/components/soc/esp32s2/. -IC:/Users/iau/esp/esp-idf/components/soc/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/hal/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/hal/include -IC:/Users/iau/esp/esp-idf/components/esp_rom/include -IC:/Users/iau/esp/esp-idf/components/esp_rom/esp32s2 -IC:/Users/iau/esp/esp-idf/components/esp_common/include -IC:/Users/iau/esp/esp-idf/components/esp_system/include -IC:/Users/iau/esp/esp-idf/components/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/driver/include -IC:/Users/iau/esp/esp-idf/components/driver/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/esp_ringbuf/include -IC:/Users/iau/esp/esp-idf/components/efuse/include -IC:/Users/iau/esp/esp-idf/components/efuse/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/xtensa/include -IC:/Users/iau/esp/esp-idf/components/xtensa/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/espcoredump/include -IC:/Users/iau/esp/esp-idf/components/esp_timer/include -IC:/Users/iau/esp/esp-idf/components/esp_ipc/include -IC:/Users/iau/esp/esp-idf/components/esp_pm/include -IC:/Users/iau/esp/esp-idf/components/vfs/include -IC:/Users/iau/esp/esp-idf/components/esp_wifi/include -IC:/Users/iau/esp/esp-idf/components/esp_wifi/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/esp_event/include -IC:/Users/iau/esp/esp-idf/components/esp_netif/include -IC:/Users/iau/esp/esp-idf/components/esp_eth/include -IC:/Users/iau/esp/esp-idf/components/tcpip_adapter/include -IC:/Users/iau/esp/esp-idf/components/app_trace/include -IC:/Users/iau/esp/esp-idf/components/nvs_flash/include -IC:/Users/iau/esp/esp-idf/components/spi_flash/include -IC:/Users/iau/esp/esp-idf/components/mbedtls/port/include -IC:/Users/iau/esp/esp-idf/components/mbedtls/mbedtls/include -IC:/Users/iau/esp/esp-idf/components/mbedtls/esp_crt_bundle/include -IC:/Users/iau/esp/esp-idf/components/mqtt/esp-mqtt/include -IC:/Users/iau/esp/esp-idf/components/nghttp/port/include 
-IC:/Users/iau/esp/esp-idf/components/nghttp/nghttp2/lib/includes -IC:/Users/iau/esp/esp-idf/components/tcp_transport/include -IC:/Users/iau/esp/esp-idf/components/esp-tls -IC:/Users/iau/esp/esp-idf/components/esp-tls/esp-tls-crypto -IC:/Users/iau/esp/esp-idf/components/esp_http_server/include -IC:/Users/iau/esp/esp-idf/components/json/cJSON -mlongcalls   -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -std=gnu++11 -fexceptions -fno-rtti -D_GNU_SOURCE -DIDF_VER=\"v4.3-dirty\" -DESP_PLATFORM -std=gnu++2a -MD -MT esp-idf/essentials/CMakeFiles/__idf_essentials.dir/source/wifi.cpp.obj -MF esp-idf\essentials\CMakeFiles\__idf_essentials.dir\source\wifi.cpp.obj.d -o esp-idf/essentials/CMakeFiles/__idf_essentials.dir/source/wifi.cpp.obj -c ../components/essentials/source/wifi.cpp
../components/essentials/source/wifi.cpp: In member function 'void essentials::Wifi::Private::connect(std::string_view, std::string_view)':
../components/essentials/source/wifi.cpp:51:62: error: cannot convert 'esp_interface_t' to 'wifi_interface_t'
     error |= esp_wifi_set_config(ESP_IF_WIFI_STA, &wifiConfig);
                                                              ^
In file included from ../components/essentials/source/wifi.cpp:5:
C:/Users/iau/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:799:48: note:   initializing argument 1 of 'esp_err_t esp_wifi_set_config(wifi_interface_t, wifi_config_t*)'
 esp_err_t esp_wifi_set_config(wifi_interface_t interface, wifi_config_t *conf);
                               ~~~~~~~~~~~~~~~~~^~~~~~~~~
../components/essentials/source/wifi.cpp: In member function 'void essentials::Wifi::Private::startAccessPoint(std::string_view, std::string_view, essentials::Wifi::Channel)':
../components/essentials/source/wifi.cpp:114:61: error: cannot convert 'esp_interface_t' to 'wifi_interface_t'
     error |= esp_wifi_set_config(ESP_IF_WIFI_AP, &wifiConfig);
                                                             ^
In file included from ../components/essentials/source/wifi.cpp:5:
C:/Users/iau/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:799:48: note:   initializing argument 1 of 'esp_err_t esp_wifi_set_config(wifi_interface_t, wifi_config_t*)'
 esp_err_t esp_wifi_set_config(wifi_interface_t interface, wifi_config_t *conf);
                               ~~~~~~~~~~~~~~~~~^~~~~~~~~
[855/865] Building CXX object esp-idf/essentials/CMakeFiles/__idf_essentials.dir/source/mqtt.cpp.obj
ninja: build stopped: subcommand failed.
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake --build ." terminated with exit code: 1.
```

Again, this is with the blink.c main code.


```
# The following five lines of boilerplate have to be in your project's
# CMakeLists in this exact order for cmake to work correctly
cmake_minimum_required(VERSION 3.5)

set(CMAKE_CXX_STANDARD 20) # <--

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(blink)

target_add_binary_data(${CMAKE_PROJECT_NAME}.elf "components/essentials/resources/web/dist/app.js.gz" TEXT) # <-- (only needed by `essentials::SettingsServer`)
target_add_binary_data(${CMAKE_PROJECT_NAME}.elf "components/essentials/resources/web/dist/index.html.gz" TEXT) # <-- (only needed by `essentials::SettingsServer`)
```


```
idf_component_register(
    SRCS "blink.c"
    INCLUDE_DIRS "."
    REQUIRES essentials
                   )
```

**Comment by lubosmato** [comment]
Hi Rudy, it looks like you are using the newest version of esp-idf v4.3 and this project is compatible with esp-idf v4.1. 

However migration to v4.3 is really trivial so I have updated the project now. Please pull repo and it should start working properly.

**Comment by RudyFiero** [comment]
After my last post I found that it had changed in 4.3. In 4.2 was the earlier way.  I'm really glad that you were able to look at this so quickly. 

I am not a programmer. I a hardware developer. Up until now I have mainly been using the Arduino IDE because it is so easy. Working with the ESP-IDF has been a real struggle for me. 

I am more than a little confused with how to include your code into an existing project. Your instructions were to include it as a component under a project. That makes perfect sense to me. As far as your examples, do I use the example files as the 'main.c' file?

**Comment by lubosmato** [comment]
I am glad I could help.

To use example code, copy contents of example file and put it into `main.c` and rename `main.c` to `main.cpp`. This way you tell compiler to use C++ compiler for the file. 

Or you can simply clone this repo https://github.com/lubosmato/esp32-essentials-example and update submodules. It is a wifi example with everything prepared for prototyping.

**Comment by RudyFiero** [comment]
Figured it out. I forgot to enable C++ exceptions. 

It also asks for Emergency Pool Size. Size (in bytes) of the emergency memory pool for C++ exceptions. This pool will be used to allocate memory for thrown exceptions when there is not enough memory on the heap.

I didn't know what it should be so I just put in 512. Should I use a different amount?

-------------------------------------------------------------------------------
Another problem. Previously I had not modified the main.c code because I wasn't certain I would have introduced a mistake. It was just to see if it would complete a compile. This time I used your examples as the main code.

 I wasn't sure I did the pull correctly so I started did the following. First, what I had done, was setup a new directory with the blink.c code. I then added your code as a component and changed the Cmake files. 

I then took the device_info.cpp code and copied it into main.cpp.  I then got the error below.  I then had replaced the  device_info.cpp in main.cpp with the example code wifi.cpp. Again I got the same error.


[89/89] Generating binary image from built executable
esptool.py v3.1-dev
Merged 1 ELF section
Generated C:/Users/iau/try1/blink/build/bootloader/bootloader.bin
[997/1014] Building CXX object esp-idf/essentials/CMakeFiles/__idf_essentials.dir/source/esp32_storage.cpp.obj
FAILED: esp-idf/essentials/CMakeFiles/__idf_essentials.dir/source/esp32_storage.cpp.obj 
C:\Users\iau\.espressif\tools\xtensa-esp32s2-elf\esp-2020r3-8.4.0\xtensa-esp32s2-elf\bin\xtensa-esp32s2-elf-g++.exe  -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -Iconfig -I../components/essentials/include -IC:/Users/iau/esp/esp-idf/components/newlib/platform_include -IC:/Users/iau/esp/esp-idf/components/freertos/include -IC:/Users/iau/esp/esp-idf/components/freertos/port/xtensa/include -IC:/Users/iau/esp/esp-idf/components/esp_hw_support/include -IC:/Users/iau/esp/esp-idf/components/esp_hw_support/port/esp32s2/. -IC:/Users/iau/esp/esp-idf/components/esp_hw_support/port/esp32s2/private_include -IC:/Users/iau/esp/esp-idf/components/heap/include -IC:/Users/iau/esp/esp-idf/components/log/include -IC:/Users/iau/esp/esp-idf/components/lwip/include/apps -IC:/Users/iau/esp/esp-idf/components/lwip/include/apps/sntp -IC:/Users/iau/esp/esp-idf/components/lwip/lwip/src/include -IC:/Users/iau/esp/esp-idf/components/lwip/port/esp32/include -IC:/Users/iau/esp/esp-idf/components/lwip/port/esp32/include/arch -IC:/Users/iau/esp/esp-idf/components/soc/include -IC:/Users/iau/esp/esp-idf/components/soc/esp32s2/. -IC:/Users/iau/esp/esp-idf/components/soc/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/hal/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/hal/include -IC:/Users/iau/esp/esp-idf/components/esp_rom/include -IC:/Users/iau/esp/esp-idf/components/esp_rom/esp32s2 -IC:/Users/iau/esp/esp-idf/components/esp_common/include -IC:/Users/iau/esp/esp-idf/components/esp_system/include -IC:/Users/iau/esp/esp-idf/components/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/driver/include -IC:/Users/iau/esp/esp-idf/components/driver/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/esp_ringbuf/include -IC:/Users/iau/esp/esp-idf/components/efuse/include -IC:/Users/iau/esp/esp-idf/components/efuse/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/xtensa/include -IC:/Users/iau/esp/esp-idf/components/xtensa/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/espcoredump/include -IC:/Users/iau/esp/esp-idf/components/esp_timer/include -IC:/Users/iau/esp/esp-idf/components/esp_ipc/include -IC:/Users/iau/esp/esp-idf/components/esp_pm/include -IC:/Users/iau/esp/esp-idf/components/vfs/include -IC:/Users/iau/esp/esp-idf/components/esp_wifi/include -IC:/Users/iau/esp/esp-idf/components/esp_wifi/esp32s2/include -IC:/Users/iau/esp/esp-idf/components/esp_event/include -IC:/Users/iau/esp/esp-idf/components/esp_netif/include -IC:/Users/iau/esp/esp-idf/components/esp_eth/include -IC:/Users/iau/esp/esp-idf/components/tcpip_adapter/include -IC:/Users/iau/esp/esp-idf/components/app_trace/include -IC:/Users/iau/esp/esp-idf/components/nvs_flash/include -IC:/Users/iau/esp/esp-idf/components/spi_flash/include -IC:/Users/iau/esp/esp-idf/components/mbedtls/port/include -IC:/Users/iau/esp/esp-idf/components/mbedtls/mbedtls/include -IC:/Users/iau/esp/esp-idf/components/mbedtls/esp_crt_bundle/include -IC:/Users/iau/esp/esp-idf/components/mqtt/esp-mqtt/include -IC:/Users/iau/esp/esp-idf/components/nghttp/port/include -IC:/Users/iau/esp/esp-idf/components/nghttp/nghttp2/lib/includes -IC:/Users/iau/esp/esp-idf/components/tcp_transport/include -IC:/Users/iau/esp/esp-idf/components/esp-tls -IC:/Users/iau/esp/esp-idf/components/esp-tls/esp-tls-crypto -IC:/Users/iau/esp/esp-idf/components/esp_http_server/include -IC:/Users/iau/esp/esp-idf/components/json/cJSON -mlongcalls   -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -std=gnu++11 -fno-exceptions -fno-rtti -D_GNU_SOURCE -DIDF_VER=\"v4.3-dirty\" -DESP_PLATFORM -std=gnu++2a -MD -MT esp-idf/essentials/CMakeFiles/__idf_essentials.dir/source/esp32_storage.cpp.obj -MF esp-idf\essentials\CMakeFiles\__idf_essentials.dir\source\esp32_storage.cpp.obj.d -o esp-idf/essentials/CMakeFiles/__idf_essentials.dir/source/esp32_storage.cpp.obj -c ../components/essentials/source/esp32_storage.cpp
../components/essentials/source/esp32_storage.cpp: In member function 'virtual std::vector<unsigned char> essentials::Esp32Storage::read(std::string_view, int) const':
../components/essentials/source/esp32_storage.cpp:34:60: error: exception handling disabled, use -fexceptions to enable
     throw std::runtime_error(**"error while getting NVS blob"**);
                                                            ^
[1004/1014] Building CXX object esp-idf/essentials/CMakeFiles/__idf_essentials.dir/source/mqtt.cpp.obj
ninja: build stopped: subcommand failed.
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake --build ." terminated with exit code: 1.

I expect this is again a version problem. The last time the reported error gave me something to look for. I don't know what to do with this error. Hopefully it is trivial.

**Comment by RudyFiero** [comment]
I forgot to enable C++ exceptions. 

It also asks for Emergency Pool Size.  Size (in bytes) of the emergency memory pool for C++ exceptions. This pool will be used to allocate memory for thrown exceptions when there is not enough memory on the heap.

I didn't know what it should be so I just put in 512. Should I use a different amount?

**Comment by RudyFiero** [comment]
It compiles. I am able to get AP with the setup webpage. I'm very happy about that.

The ESP does not connect to my router. I don't know why. I will close this issue and open a new one for that.

**Comment by lubosmato** [comment]
512 is good value. Emergency Pool Size reserves memory on heap for exception handling so you reserved 512 bytes for exception handling.

Exception handling needs to allocate heap memory and if there is no memory left esp32 device would crash. But if you set emergency pool size there will always be reserved memory for exception handling.
